### ISSUE TITLE
Adding argparse to simplify usage

### ISSUE THREAD

**Issue by pard68** [emilmerle/FindingThingsWithPython#13]
How would you feel about adding argparse to simplify the usage and consolidate code.

My idea is something like

`python ftwp/app.py --email --to-clipboard /path/to/file`

This would then look for emails in the file and send those emails to the clipboard for usage. Wanted to get your opinion on this, since it's a substantial change, before I went ahead and created a PR. Feel free to assign this issue to me. I already have a portion of this done.

**Comment by emilmerle** [comment]
This is a good idea and it may be easier to use but I feel like it does not really fit in this repository. 
I want a simple repo that is easy to understand and I think for the comprehensibility it is not helpful.
Since this is a repo for beginners, "easy to understand" is more important than "easy to use".
Although thank you for your participation and contribution :)
Keep it up and good luck!
